# Change these first
owner: DeltaGaming-org # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Web Service
    url: https://deltagaming.org
    icon: https://raw.githubusercontent.com/DeltaGaming-org/status/master/static/server.svg
  - name: Game Service
    url: $FIVEM_SERVER
    icon: https://raw.githubusercontent.com/DeltaGaming-org/status/master/static/server.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  cname: status.deltagaming.org
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/attachments/930355225007652884/947625013383671830/testdelta.png
  favicon: https://raw.githubusercontent.com/DeltaGaming-org/status/master/assets/delta-logo.ico
  name: Delta Gaming Status
  introTitle: "**Delta Gaming** is an Australian based FiveM roleplay community based in New South Wales, Australia."
  introMessage: This is Delta Gaming's real-time status page.
  navbar:
    - title: Status
      href: /
    - title: Forum
      href: https://deltagaming.org
    - title: Discord
      href: https://discord.gg/deltagaming
notifications:
  NOTIFICATION_DISCORD: true
  NOTIFICATION_DISCORD_WEBHOOK: true
  NOTIFICATION_DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
